service: serverless-authorizers
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-central-1

plugins:
  - serverless-offline

functions:
  login:
    handler: src/auth/authorizer.login
    events:
      - http:
          path: login
          method: POST
          cors: true

  registration:
    handler: src/auth/authorizer.registration
    events:
      - http:
          path: registration
          method: POST
          cors: true

  createComment:
    handler: src/domains/domains.createComment
    events:
      - http:
          path: comment
          method: POST
          cors: true

  getDomains:
    handler: src/domains/domains.getDomains
    events:
      - http:
          path: domains
          method: POST
          cors: true

  me:
    handler: src/auth/authorizer.me
    events:
      - http:
          path: me
          method: GET
          cors: true

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'